import type { Metadata } from 'next';
import { MainLayout } from '@/components/main-layout';
import { SWPCalculator } from '@/components/swp-calculator';
import { FAQSection } from '@/components/faq-section';

export const metadata: Metadata = {
  title: 'SWP Calculator | Bunny Calculator',
  description: 'Calculate your Systematic Withdrawal Plan (SWP) returns. Plan your retirement income, estimate future balances, and withdraw smartly.',
  keywords: 'swp calculator, systematic withdrawal plan, retirement income calculator, mutual fund withdrawal',
};

const faqs = [
  {
    question: 'What is a Systematic Withdrawal Plan (SWP)?',
    answer: 'SWP allows you to withdraw a fixed amount of money at regular intervals from your mutual fund investment. While you withdraw, your remaining balance continues to earn returns.'
  },
  {
    question: 'How is the final remaining amount calculated?',
    answer: 'The final amount is calculated by taking your initial investment, adding the monthly interest generated by the remaining balance, and subtracting your fixed monthly withdrawal over the specified period.'
  },
  {
    question: 'Why is SWP better than dividend payouts?',
    answer: 'SWP gives you complete control over your cash flow because you choose the exact withdrawal amount. Additionally, SWP withdrawals from equity funds are often more tax-efficient compared to dividend income.'
  }
];

export default function SWPPage() {
  return (
    <MainLayout>
      <div className="px-6 py-12">
        <div className="max-w-5xl mx-auto space-y-12">
          {/* Header */}
          <div>
            <h1 className="text-4xl font-bold text-foreground mb-4">
              SWP Calculator (Systematic Withdrawal Plan)
            </h1>
            <p className="text-lg text-muted-foreground">
              Calculate the final value of your investment after regular systematic withdrawals and see how long your money will last.
            </p>
          </div>

          <SWPCalculator />

          {/* Educational Content for SEO & User Guide */}
          <div className="pt-12 border-t border-border">
            <h2 className="text-2xl font-bold mb-4">How Does the SWP Calculator Help You?</h2>
            <p className="text-muted-foreground mb-4">
              A Systematic Withdrawal Plan is perfect for retirees or anyone needing a regular monthly income from their accumulated corpus.
              Our <strong>SWP Calculator</strong> estimates your remaining balance over time to ensure you don't deplete your funds too quickly.
            </p>

            <div className="grid md:grid-cols-2 gap-8 mt-8">
              <div className="bg-secondary/10 p-6 rounded-2xl border border-secondary/20">
                <h3 className="text-xl font-bold text-foreground mb-4">How to Use</h3>
                <ol className="space-y-3 text-muted-foreground">
                  <li><strong>Initial Investment:</strong> Enter the total amount you currently have invested.</li>
                  <li><strong>Monthly Withdrawal:</strong> The fixed amount you plan to withdraw every month.</li>
                  <li><strong>Expected Return:</strong> The realistic annual rate your remaining investment will earn.</li>
                  <li><strong>Duration:</strong> The number of months you wish to withdraw this income.</li>
                </ol>
              </div>

              <div className="bg-primary/5 p-6 rounded-2xl border border-primary/10">
                <h3 className="text-xl font-bold text-foreground mb-4">How SWP Mathematically Works</h3>
                <p className="text-sm text-muted-foreground mb-3">
                  In an SWP, two things happen simultaneously every month:
                </p>
                <div className="bg-background border border-border p-4 rounded-lg font-mono text-primary text-sm mb-4">
                  Balance = (Previous Balance + Monthly Interest) - Withdrawal
                </div>
                <ul className="text-sm space-y-2 text-muted-foreground">
                  <li><strong>Capital Appreciation:</strong> Your remaining corpus continues to compound.</li>
                  <li><strong>Depletion:</strong> Your monthly extraction slightly lowers the base for next month's compounding.</li>
                  <li><strong>Tax Efficiency:</strong> You only pay capital gains tax on the profit portion of your withdrawal.</li>
                </ul>
              </div>
            </div>

            <h3 className="text-xl font-bold mt-10 mb-4">Why Choose SWP for Regular Income?</h3>
            <div className="grid sm:grid-cols-3 gap-6 text-sm">
              <div className="p-4 border border-border rounded-xl">
                <div className="text-2xl mb-2">💸</div>
                <strong className="block text-foreground mb-1">Predictable Cash Flow</strong>
                <span className="text-muted-foreground">Set up a fixed "salary" for yourself directly from your investments.</span>
              </div>
              <div className="p-4 border border-border rounded-xl">
                <div className="text-2xl mb-2">🌱</div>
                <strong className="block text-foreground mb-1">Continued Growth</strong>
                <span className="text-muted-foreground">Unlike bank FDs, your unwithdrawn money stays invested in mutual funds yielding returns.</span>
              </div>
              <div className="p-4 border border-border rounded-xl">
                <div className="text-2xl mb-2">🛡️</div>
                <strong className="block text-foreground mb-1">Beat Inflation</strong>
                <span className="text-muted-foreground">Market-linked returns from the remaining corpus help protect your overall purchasing power.</span>
              </div>
            </div>
          </div>

          <FAQSection faqs={faqs} />
        </div>
      </div>
    </MainLayout>
  );
}
